use_frameworks!

platform :ios, '13.0'

target 'MMTToolForNordicTool_Example' do
  pod 'MMTToolForNordicTool', :path => '../'
  
  pod 'ZIPFoundation'
  pod 'MMTToolForGoodixDFU'

  target 'MMTToolForNordicTool_Tests' do
    inherit! :search_paths

    
  end
end
